### ISSUE TITLE
Training configuration

### ISSUE THREAD

**Issue by yangyefd** [zoenguyenramirez/arc-prize-2024#1]
Thank you for your excellent work. I’d like to ask, what kind of configuration is required for this training, and how much VRAM is sufficient?

**Comment by zoenguyenramirez** [comment]
I can confirm it's quite flexible in terms of hardware requirements. Here's how you can adjust the configuration:

1. Memory Optimization (see [this commit](https://github.com/zoenguyenramirez/arc-prize-2024/commit/eb75357e5de1e6a614ed6ee1a5ae6f0aa8a221d0)):
   - Adjust `accumulation-steps` and `batch-size` to significantly reduce memory requirements

2. Key Parameters you can tune:
   ```
   --max-seq-length 2480   # Reduces attention tensor size and memory usage
   --num-layers 18         # Even 7 layers can solve many problems
   --embed-size 888        # Started from 64 for basic synthetic tasks
   ```

3. Notable Features:
   - Context window is flexible - you can train with 2480 tokens but solve tasks requiring 3000+ tokens
   - For quick testing, check the [sanity check script](https://github.com/zoenguyenramirez/arc-prize-2024/blob/main/dev_folder/scripts/sanity_check.sh)
   - Can achieve convergence in 1 minute for synthetic tasks (e.g., even/odd recognition)
   - Should run well on most GPUs with proper parameter tuning

4. Hardware Requirements:
   - 8GB VRAM should be sufficient for experimentation
   - I used 2-3 RTX 4090s during the competition

5. Future Exploration:
   I'd be interested to see results with more ambitious parameters:
   ```
   --max-seq-length 8000   # Too computationally intensive on 2x 4090 during competition
   --embed-size 2000       # Haven't tested this configuration yet
   ```

**Comment by yangyefd** [comment]
Thank you for taking the time to explain this.
